config/routes.rb
Rails.application.routes.draw do
  root to:'welcome#show'

  get 'team', to: 'team#show'
  get 'contact', to: 'contact#show'
  get 'welcome/', to: 'welcome#show'
  get 'welcome/:first_name', to: 'welcome#show'
  get 'gossips/:id', to: 'gossip#gossip', as:'gossip'

  get 'profile/:first_name', to: 'profile#profile', as: 'profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  #has_many :users, through: :comments
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  belongs_to :city
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  #has_many :gossips, through: :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def gossip
    id = params[:id]
    @gossip = Gossip.find_by(:id => id)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def profile
    @user = User.find_by(:first_name => params[:first_name])
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
    puts 'voici notre equipe lol mdr'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
      puts "démarrage"
     @first_name = params[:first_name]
     puts "Ceci est mon super params : #{params}"
     puts "Trop bien ! Et ceci est ce que l'utilisateur a passé dans tel champ : #{params["first_name"]}"
     # @images  = ["https://www.bootdey.com/img/Content/user_1.jpg", "https://www.bootdey.com/img/Content/user_2.jpg", "https://www.bootdey.com/img/Content/user_3.jpg"]
     # @random_no = rand(3)
     # @random_image = @images[@random_no]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/turlute_helper.rb
module TurluteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Gossip Project</title>
  </head>

  <body>
  <div class="container mt-5">
  <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="<%= asset_path('bis.png') %>" alt="BIS">
  <div class="card-body">
    <h5 class="card-title">Comment nous rejoindre?</h5>
    <p class="card-text">Retrouvez-nous sur notre serveur discord.</p>
    <a href="https://discord.gg/hXdpu9j" class="btn btn-primary">Allez Viens</a>
  </div>
</div>
  </div>

    <%= yield %>
  </body>
</html>

app/views/gossip/gossip.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>The Gossip Project</title>
</head>

<body>

  <div class="container mt-4">
    <h4>Potin:</h4>

    <div class="row">
      <div class="card border-success mb-3" style="max-width: 18rem;">
        <div class="card-header">
          <%= link_to "Auteur: " + @gossip.user.first_name , profile_path(:first_name => @gossip.user.first_name)%></p>
        </div>
        <div class="card-body">
          <p class="card-text">Id: <%=  @gossip.id %></p>
          <p class="card-text">Titre: <%=  @gossip.title  %></p>
          <p class="card-text">Contenu: <%=  @gossip.content %></p>
          <p class="card-text">Date de création: <%=  @gossip.created_at %></p>
        </div>
      </div>
    </div>
  </div>
</body>

</html>

app/views/team/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>The Gossip Project</title>
</head>

<body>
  <h2 class="mt-4 mb-4 ml-3">Notre équipe</h2>

  <div class="container">
    <div class="row">

      <div class="col-sm-6 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <a href="https://github.com/StanislasBASQUIN">✌️
                Stanislas BASQUIN
              </a>
            </div>
          </div>
        </div>
      </div>


      <div class="col-sm-6 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <a href="https://github.com/tienduy-nguyen">🧞‍♂️
                Tien Duy NGUYEN
              </a>
            </div>
          </div>
        </div>
      </div>


      <div class="col-sm-6 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <a href="https://github.com/HugoPeranSejourne">😺
                Hugo Péran Séjourné
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-6 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <a href="https://github.com/mathieu-superpose">🤓
                Mathieu JOLY
              </a>
            </div>
          </div>
        </div>
      </div>


      <div class="col-sm-6 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <a href="https://github.com/Vivien-Ploix">👍
                Vivien Ploix
              </a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-6 mb-3">
        <div class="card">
          <div class="card-body">
            <div class="card-text">
              <a href="https://github.com/barifche">👻
                Chérif BA
              </a>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>



  <%= yield %>
</body>

</html>

app/views/welcome/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <% content_for :title, "Welcome" %>
</head>
<body>


  <!-- MAIN BODY -->
  <section id="gossip-section" class="py-1 mb-5" style="margin-top: 50px">
    <div class="container mt-2">
      <h1>Welcome <%= @first_name %> </h1>

      <h4 class="mb-5 mt-3">Voici la liste de potins de tous moussaillons chez THP</h4>
        <div class="row mb-3">
      <% Gossip.all.each do |gossip|%>
    

        <div class="col-md-6 mb-2">
          <div class="card p-2">
            <div class="card-heading d-flex">
              <div class="pull-left d-flex author">
                <div class="pull-left mr-2">
                  <img src="http://bootdey.com/img/Content/user_1.jpg" class="rounded-circle img-fluid"
                    alt="user profile image" style="height:40px;width:40px">
                </div>
                <div class=" pt-1" style="positon: relative">
                  <%= link_to gossip.user.first_name, profile_path(:first_name => gossip.user.first_name ), :class =>'h5'%>
                  
                  <br><small class="text-muted"
                    style="margin-top:-1px;position:absolute"><sup><%= gossip.created_at %></sup></small>
                </div>
              </div>
            </div>

            <div class="card-body ">
              Gossip n° <%= gossip.id.to_s%>: <%= link_to  gossip.title, gossip_path(:id => gossip.id) %>
            </div>

          </div>
        </div>
      <%end%>
      </div>
    </div>
  </section>

</body>

</html>