config/routes.rb
Rails.application.routes.draw do
  root to:'welcome#show'

  get 'team', to: 'team#show'
  get 'contact', to: 'contact#show'
  get 'welcome/', to: 'welcome#show'
  get 'welcome/:first_name', to: 'welcome#show'
  get 'gossips/:id', to: 'gossip#gossip', as:'gossip'

  get 'profile/:first_name', to: 'profile#profile', as: 'profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags
  has_many :comments
  #has_many :users, through: :comments
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  has_many :gossips
  belongs_to :city
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
  has_many :comments
  #has_many :gossips, through: :comments
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  def gossip
    id = params[:id]
    @gossip = Gossip.find_by(:id => id)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def profile
    @user = User.find_by(:first_name => params[:first_name])
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
    puts 'voici notre equipe lol mdr'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
      puts "démarrage"
     @first_name = params[:first_name]
     puts "Ceci est mon super params : #{params}"
     puts "Trop bien ! Et ceci est ce que l'utilisateur a passé dans tel champ : #{params["first_name"]}"
     # @images  = ["https://www.bootdey.com/img/Content/user_1.jpg", "https://www.bootdey.com/img/Content/user_2.jpg", "https://www.bootdey.com/img/Content/user_3.jpg"]
     # @random_no = rand(3)
     # @random_image = @images[@random_no]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active_class(link_path)
    current_page?(link_path) ? "active" : ""
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/turlute_helper.rb
module TurluteHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | The Gossips Project</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
    crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
  
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="main-nav">
    <div class="container">
     <a class="navbar-brand" href="/">Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= active_class(root_path) %>">
       <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= active_class(team_path) %>">
          <%= link_to "Team", team_path, class: "nav-link" %>
      </li>
      <li class="nav-item <%= active_class(contact_path) %>">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
    </ul>

    </div>
    </div>

</nav>

<!-- Main content of body -->
<div class="container">
  <%= yield %>
</div>

  <!-- FOOTER -->
  <footer id="main-footer" class="text-center pt-3 pb-0 mb-0 bg-light bg-dark text-white">
    <div class="container">
      <div class="row">
        <div class="col">
          <p>Copyright &copy;
            <span id="year"></span> The Best Team</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Script -->
  <script src="http://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" crossorigin="anonymous">
  </script>
  <script>
    $('#year').text(new Date().getFullYear());
  </script>

</body>
</html>